# Generated by Django 3.2.15 on 2022-10-14 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиента не может быть нулевым'), django.core.validators.MaxValueValidator(100, message='Количество ингредиента не может быть больше ста')], verbose_name='количество'),
        ),
    ]
